### ISSUE TITLE
fixed/broke AUTH not working with oauth2/oidc

### ISSUE THREAD

**Issue by snoopotic** [arbourd/concourse-slack-alert-resource#60] opened 2020-01-21 12:45 UTC
Hi, 
we're using an oauth2 provider for our authentication of our teams/members.

It seems the authentication for the fixed/broke notifications does not work. We're getting:

> 2020/01/21 12:22:55 error getting last build status: error connecting to Concourse: oauth2: cannot fetch token: 401 Unauthorized
> 
> Response: 

Yes: Reponse is empty. Logging says:
`{"timestamp":"2020-01-21T12:22:55.008878894Z","level":"error","source":"atc","message":"atc.sky.token.failed-to-fetch-dex-token","data":{"error":"oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"access_denied\",\"error_description\":\"Invalid username or password\"}","session":"7.5653"}}
{"timestamp":"2020-01-21T12:22:55.015407688Z","level":"error","source":"atc","message":"atc.sky.token.invalid-basic-auth","data":{"session":"7.5654"}}`

Do you have an Idea how to solve that or du debug it better? 
Thanks,
Felix

**Comment by arbourd** [comment] 2020-05-11 13:51
Hi Felix (@snoopotic). Sorry about the delay, but I was on leave. Are you still having this issue? Any ideas on how to fix it?

**Comment by arbourd** [comment] 2020-05-30 16:30
Cannot reproduce this so I'm closing for now. Please let me know if you still have issues. Looks like the username/password may have been set improperly.

**Closed by arbourd** 2020-05-30 16:30 UTC

**Comment by qlikcoe** [comment] 2021-03-26 16:45
@arbourd  We are now having this issue with Concourse 7... 
Using slack alert resource 0.14.1

**Comment by arbourd** [comment] 2021-03-26 18:23
Hey @qlikcoe! Long time no see. Could you make a new issue for this? It's probably related to new changes to the Concourse stuff again kinda happens with every major update. 😁

Is this something you or your team would be willing to help with? I can kinda show you folks if you're interested. Hope things are well. ❤️
